### ISSUE TITLE
捉个虫

### ISSUE THREAD

**Issue by zhbzhbzhbz** [LandGrey/pydictor#10]
regex function
Usage : --regex [regex]
Example: **--types** "^z.*?g$"
这里的--types应该是--regex

以及请问，
types function
Usage : --types [letters_types_range] [digital_types_range] [special_types_range]
Example: --types "<=8" "<=4" "=0"
如果想要所有大写+小写字母+所有数字+无特殊符号，这里的letters_types_range应该怎么写?

**Comment by LandGrey** [comment]
所有大写+小写字母+所有数字+无特殊符号，完整的过滤条件这样写：

`--types ">=0" ">=0" "==0"`

letters_types_range 部分是
`>=0`

**Comment by zhbzhbzhbz** [comment]
谢谢~可以关闭了
