### ISSUE TITLE
Repeat parameter not working properly

### ISSUE THREAD

**Issue by rube200** [LandGrey/pydictor#11]
I executed this command: 
`python pydictor.py -b dL -o "~/passwords.txt" --len 12 12 --repeat "<=3" "<=3" "<=0"`
(to long)
base_file:
```
000000000000
000000000001
000000000002
000000000003
000000000004
000000000005
000000000006
...
```

Isn't the 0 just supposed to appear up to 3 times in a row?

**Comment by LandGrey** [comment]
**thanks for your feedback**

- for high efficiency purpose, `-base` is not designed supported `--repeat` options.

- you can find descriptions in [README.md](https://github.com/LandGrey/pydictor/blob/master/README.md) file,  `-base` supported functions is `F1 F2 F3 F4` and `repeat` function is `F10`, there is no supported.

- but you can executed two command to get your wordlist:

```
python pydictor.py -b dL -o "~/passwords.txt" --len 12 12
python pydictor.py -tool handler "~/passwords.txt" --repeat "<=3" "<=3" "<=0" -o "~/passwords-repeat.txt"
```

**Comment by rube200** [comment]
Thanks, I didn't see that in [README.md](https://github.com/LandGrey/pydictor/blob/master/README.md)
