### ISSUE TITLE
how do i create a wordlist that only have 2 numbers and the rest are lowercase alphabet and it's length should be 8 ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [LandGrey/pydictor#15]
just like this
1d5ghlbz

**Comment by LandGrey** [comment]
Two step to get your wordlist:
```
python pydictor -base dL --len 8 8 -o init.dic
python pydictor -tool handler init.dic --occur "==6" "==2" "==0" -o final.dic
```
but there is huge items in `init.dic`，there will be generate `36^8 = 2.8211099e+12` lines，It will take a very long time.

**Comment by minanagehsalalma** [comment]
Hmm... thanks mate... can you explain the commands a little bit.



> but there is huge items in `init.dic`，

But i don't have  that kind of space.

Is there a way to generate the final.dic directly?

**Comment by minanagehsalalma** [comment]
Also can the letters occur be two numbers 
Not just one 
So this "--occur "==6""

Be like this 
"--occur "==6/7" and "==1/2"

**Comment by LandGrey** [comment]
No way to directly generate the final.dic so far, except to modifying the code.

**Comment by minanagehsalalma** [comment]
> except to modifying the code.

Hmm which part ;)

I think it can some how be generated using hash cat masks.

Something like this 
?l?d?l?l?l?d?l?l

But i do need to redo it many times to ensure the two numbers are every where in the wordlist ... i don't even know if it can be used to output into a wordlist.

**Comment by minanagehsalalma** [comment]
Or maybe using policygen but i don't know how to convert a mask to a wordlist.

https://tools.kali.org/password-attacks/pack
