### ISSUE TITLE
Can we generate custom wordlist by masking characters ?u?l?d

### ISSUE THREAD

**Issue by mujtabaxd** [LandGrey/pydictor#19]
@LandGrey 
### ABC12A34B56 - Required Pattern
This is the pattern that i'm generating but i don't understand how to use the charactersets.

`pydictor.py --head abc --len 8 8 -char ?d?d?l?d?d?l?d?d - o output.txt`

When i press enter, i get this result `abc?d?d?l?d?d?l?d?d ` in wordlist instead of actual digits and letters.

**output.txt**

```
abc???l????
abc???l???d
abc???l????
abc???l???d
abc???l??l?
abc???l??ld
abc???l??l?
abc???l??ld
abc???l??l?
abc???l??ll
abc???l??l?
abc???l??ld
abc???l??l?
abc???l??ld
abc???l??l?
abc???l??ll
abc???l??l?
abc???l??ld
abc???l??l?
abc???l??ld
abc???l????
```

**Comment by LandGrey** [comment]
> @LandGrey
> 
> ### ABC12A34B56 - Required Pattern
> This is the pattern that i'm generating but i don't understand how to use the charactersets.
> 
> `pydictor.py --head abc --len 8 8 -char ?d?d?l?d?d?l?d?d - o output.txt`
> 
> When i press enter, i get this result `abc?d?d?l?d?d?l?d?d ` in wordlist instead of actual digits and letters.
> 
> **output.txt**
> 
> ```
> abc???l????
> abc???l???d
> abc???l????
> abc???l???d
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ll
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ll
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ld
> abc???l????
> ```



> @LandGrey
> 
> ### ABC12A34B56 - Required Pattern
> This is the pattern that i'm generating but i don't understand how to use the charactersets.
> 
> `pydictor.py --head abc --len 8 8 -char ?d?d?l?d?d?l?d?d - o output.txt`
> 
> When i press enter, i get this result `abc?d?d?l?d?d?l?d?d ` in wordlist instead of actual digits and letters.
> 
> **output.txt**
> 
> ```
> abc???l????
> abc???l???d
> abc???l????
> abc???l???d
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ll
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ll
> abc???l??l?
> abc???l??ld
> abc???l??l?
> abc???l??ld
> abc???l????
> ```

you can get your word list by using command :
```
pydictor.py --head abc --conf "[0-9]{2,2}<none>[a-z]{1,1}<none>[0-9]{2,2}<none>[a-z]{1,1}<none>[0-9]{2,2}<none>" -o output.txt
```
it's will generate `10*10*26*10*10*26*10*10 = 676,000,000` lines and costing very long time to finish it.

**Comment by mujtabaxd** [comment]
> > @LandGrey
> > ### ABC12A34B56 - Required Pattern
> > This is the pattern that i'm generating but i don't understand how to use the charactersets.
> > `pydictor.py --head abc --len 8 8 -char ?d?d?l?d?d?l?d?d - o output.txt`
> > When i press enter, i get this result `abc?d?d?l?d?d?l?d?d ` in wordlist instead of actual digits and letters.
> > **output.txt**
> > ```
> > abc???l????
> > abc???l???d
> > abc???l????
> > abc???l???d
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ll
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ll
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ld
> > abc???l????
> > ```
> 
> > @LandGrey
> > ### ABC12A34B56 - Required Pattern
> > This is the pattern that i'm generating but i don't understand how to use the charactersets.
> > `pydictor.py --head abc --len 8 8 -char ?d?d?l?d?d?l?d?d - o output.txt`
> > When i press enter, i get this result `abc?d?d?l?d?d?l?d?d ` in wordlist instead of actual digits and letters.
> > **output.txt**
> > ```
> > abc???l????
> > abc???l???d
> > abc???l????
> > abc???l???d
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ll
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ll
> > abc???l??l?
> > abc???l??ld
> > abc???l??l?
> > abc???l??ld
> > abc???l????
> > ```
> 
> you can get your word list by using command :
> 
> ```
> pydictor.py --head abc --conf "[0-9]{2,2}<none>[a-z]{1,1}<none>[0-9]{2,2}<none>[a-z]{1,1}<none>[0-9]{2,2}<none>" -o output.txt
> ```
> 
> it's will generate `10*10*26*10*10*26*10*10 = 676,000,000` lines and costing very long time to finish it.

Thanks for the help sir, but when i execute the above command i get the following error.

**[-] Exception as following:**

```
Traceback (most recent call last):
  File "E:\pydictor-master\lib\fun\decorator.py", line 21, in magic
    for item in unique(func()):
  File "E:\pydictor-master\lib\fun\fun.py", line 34, in unique
    seen[marker] = 1
MemoryError
None
```

**Comment by LandGrey** [comment]
> > you can get your word list by using command :
> > ```
> > pydictor.py --head abc --conf "[0-9]{2,2}<none>[a-z]{1,1}<none>[0-9]{2,2}<none>[a-z]{1,1}<none>[0-9]{2,2}<none>" -o output.txt
> > ```
> > 
> > 
> > it's will generate `10*10*26*10*10*26*10*10 = 676,000,000` lines and costing very long time to finish it.
> 
> Thanks for the help sir, but when i execute the above command i get the following error.
> 
> ```diff
> -[-] Exception as following:
> 
> Traceback (most recent call last):
>   File "E:\pydictor-master\lib\fun\decorator.py", line 21, in magic
>     for item in unique(func()):
>   File "E:\pydictor-master\lib\fun\fun.py", line 34, in unique
>     seen[marker] = 1
> MemoryError
> None
> ```

There are some like memory overload, `--conf` is only suitable for generating small customized word list.
I will try to solve this problem to quickly generating a large word list by patterns.

**Comment by mujtabaxd** [comment]
Thanks. Kindly let me know when you fix this.

**Comment by LandGrey** [comment]
> Thanks. Kindly let me know when you fix this.

Now, you can use command
```
python3 pydictor.py --head abc --pattern "[0-9]{1,1}<none>[0-9]{1,1}<none>[a-z]{1,1}<none>[0-9]{1,1}<none>[0-9]{1,1}<none>[a-z]{1,1}<none>[0-9]{1,1}<none>[0-9]{1,1}<none>" -o output.txt
```
to generate your wordlist, maybe cost 20-30 minute.

**Comment by mujtabaxd** [comment]
> > Thanks. Kindly let me know when you fix this.
> 
> Now, download the latest project, you can use command
> 
> ```
> python3 pydictor.py --head abc --pattern "[0-9]{1,1}<none>[0-9]{1,1}<none>[a-z]{1,1}<none>[0-9]{1,1}<none>[0-9]{1,1}<none>[a-z]{1,1}<none>[0-9]{1,1}<none>[0-9]{1,1}<none>" -o output.txt
> ```
> 
Thanks you sir, It's a great tool.
