### ISSUE TITLE
Password limitations

### ISSUE THREAD

**Issue by SiZiGee** [LandGrey/pydictor#2]
Hi there,

I tried creating a dictionary with 13 characters and it returned that it should be <= 11, so I changed it to 20.

Then the  count_switcher was set to 100M, so I changed it to 1,000,000,000,000,000,000,000,000.  It is creating the file, but the file has been stuck at 510MB and not increasing.

What am I missing?

Thanks and kind regards,

SiZiGee

**Comment by LandGrey** [comment]
Can you show me your pydictor cli command about your issue?
I will do again and see what happened.

**Comment by SiZiGee** [comment]
I had to reinstall my machine, as I was having some issues (haven't done so in about 3 years, it was about time... from upgrading to win 10, then from technical preview to pro... sigh).

If I remember correctly, I used -chunk abcdef1234567890 and I output it to a file.  I didn't add any other extra options to it

**Comment by SiZiGee** [comment]
oh and I used ubuntu bash on windows 10

**Comment by LandGrey** [comment]
according to your comment，you must be used [-chunk a b c d e f 1 2 3 4 5 6 7 8 9 0] command, 
  It expected to output 16!=20,922,789,888,000 lines,  I tried and abort it until it increased 12.2GB, also base on win 10 bash, it will not to be stuck.
  oh, I just change the count_switcher, don't need to modify maxlen_switcher，-chunk don't depend on lenght option. 
  so, I suggest you download the latest version of pydicotr and try again,  There's no reason to be stuck.
