### ISSUE TITLE
不可以计算两个字典的对称差吗？

### ISSUE THREAD

**Issue by RussiaVk** [LandGrey/pydictor#22]

**Comment by LandGrey** [comment]
什么叫对称差，这个功能 ？
```
python pydictor.py -tool comparer big.txt small.txt
```

**Comment by RussiaVk** [comment]
> 什么叫对称差，这个功能？
> 
> ```
> python pydictor.py -tool comparer big.txt small.txt
> ```

例如A文件是集合{1，2，3}，
B文件是集合{1}
要求得到两个文件共同部分以外的集合即{2，3}

**Comment by LandGrey** [comment]
> > 什么叫对称差，这个功能？
> > ```
> > python pydictor.py -tool comparer big.txt small.txt
> > ```
> 
> 例如A文件是集合{1，2，3}，
> B文件是集合{1}
> 要求得到两个文件共同部分以外的集合即{2，3}

就是这个功能：
```
python pydictor.py -tool comparer big.txt small.txt
```

**Comment by RussiaVk** [comment]
> python pydictor.py -tool comparer

大佬，不行啊有Bug，不能处理数字？
我的a文件和b文件每一行都是数字
处理的结果为空
![image](https://user-images.githubusercontent.com/43515485/97313454-94ca0180-18a1-11eb-8ea7-77eb6c61168e.png)
![image](https://user-images.githubusercontent.com/43515485/97313501-a7443b00-18a1-11eb-8415-37b7e38d47ef.png)

**Comment by LandGrey** [comment]
**我测试没问题，你使用的 pydictor 版本、python 版本、操作系统，命令行参数都是什么？**

<img width="624" alt="2" src="https://user-images.githubusercontent.com/16769779/97387480-0ab98180-1911-11eb-882b-6cf3e2bd27c7.png">

**Comment by LandGrey** [comment]
> > python pydictor.py -tool comparer
> 
> 大佬，不行啊有Bug，不能处理数字？
> 我的a文件和b文件每一行都是数字
> 处理的结果为空
> ![image](https://user-images.githubusercontent.com/43515485/97313454-94ca0180-18a1-11eb-8ea7-77eb6c61168e.png)
> ![image](https://user-images.githubusercontent.com/43515485/97313501-a7443b00-18a1-11eb-8415-37b7e38d47ef.png)

**我测试没问题，你使用的 pydictor 版本、python 版本、操作系统，命令行参数都是什么？**

<img width="624" alt="2" src="https://user-images.githubusercontent.com/16769779/97387480-0ab98180-1911-11eb-882b-6cf3e2bd27c7.png">

**Comment by RussiaVk** [comment]
[a.txt](https://github.com/LandGrey/pydictor/files/5450618/a.txt)
[b.txt](https://github.com/LandGrey/pydictor/files/5450619/b.txt)
win10 x64
Python 3.7.5
 pydictor 2.1.1
python pydictor.py -tool comparer a.txt b.txt

**Comment by LandGrey** [comment]
> python pydictor.py -tool comparer a.txt b.txt

2.1.1 版本有点老，不好测试，你下载最新的版本试试

**Comment by RussiaVk** [comment]
哎呀搞错了，b文件跟a文件内容一样，不好意思
