### ISSUE TITLE
-tool的UnicodeDecodeError问题

### ISSUE THREAD

**Issue by fengzhouc** [LandGrey/pydictor#24]
我在win10上使用2.0.5版本的-tool工具的时候（其他平台没试过），总会报UnicodeDecodeError，看了代码发现打开文件没有指定编码，open是依赖平台的默认编码，我指定utf-8后就没有这个问题了，建议加一下

**Comment by LandGrey** [comment]
不确定你说的问题是不是因为中文目录或者指定的文件内容有中文导致的。

现在最新版本是 `2.1.5.2` ，你可以试试还有没有这个问题。

**Comment by LandGrey** [comment]
> 我在win10上使用2.0.5版本的-tool工具的时候（其他平台没试过），总会报UnicodeDecodeError，看了代码发现打开文件没有指定编码，open是依赖平台的默认编码，我指定utf-8后就没有这个问题了，建议加一下

不确定你说的问题是不是因为中文目录或者指定的文件内容有中文导致的。

现在最新版本是 `2.1.5.2` ，你可以试试还有没有这个问题。

**Comment by fengzhouc** [comment]
中文目录跟内容中文我都写脚本处理了的，传入工具是没有中文的数据，指定编码就没问题了
![image](https://user-images.githubusercontent.com/22309037/106086851-e2366300-615d-11eb-8554-613dccbec69b.png)


2.1.5.2也是的一样的问题

**Comment by LandGrey** [comment]
> 中文目录跟内容中文我都写脚本处理了的，传入工具是没有中文的数据，指定编码就没问题了
> ![image](https://user-images.githubusercontent.com/22309037/106086851-e2366300-615d-11eb-8554-613dccbec69b.png)
> 
> 2.1.5.2也是的一样的问题

The bug has been fixed at [this commit](https://github.com/LandGrey/pydictor/commit/7440c978d04c08235bea5f038da1387e94b2338f) on pydictor `2.1.5.3` version.
