### ISSUE TITLE
Head or tail cannot start with "-"

### ISSUE THREAD

**Issue by xfl03** [LandGrey/pydictor#27]
e.g. `--tail -example`
After using this argument, following error will be shown:
```
pydictor: error: argument --tail: expected one argument
```

It looks like `-example` has been recongnized as a option, but it should be the vaule.

**Comment by LandGrey** [comment]
> e.g. `--tail -example`
> After using this argument, following error will be shown:
> 
> ```
> pydictor: error: argument --tail: expected one argument
> ```
> 
> It looks like `-example` has been recongnized as a option, but it should be the vaule.

Thank you for your program using feedback.

That's python **argparse** module [features](https://stackoverflow.com/questions/43626877/python-argparse-doesnt-take-string-option-start-with).

you can use ` --tail=-example` options to avert it.
