### ISSUE TITLE
How can add more head words?

### ISSUE THREAD

**Issue by Uraniumhazee** [LandGrey/pydictor#28]
For example i use this command.

pydictor.py --head John -char 0123456789abcdef -- len 1 1 
Works great but what if i have mode head words?

I want to use John, Mike, Jane etc more words on the head? How can i make this? 
pydictor.py --head John --head Mike --head Jane -char 0123456789abcdef -- len 1 1  Not working

I have a text file and there are names on it and all i need, use these words on the head!

Thanks

**Comment by Uraniumhazee** [comment]
@LandGrey Pleae help for this topic.
Thank you

**Comment by LandGrey** [comment]
> For example i use this command.
> 
> pydictor.py --head John -char 0123456789abcdef -- len 1 1
> Works great but what if i have mode head words?
> 
> I want to use John, Mike, Jane etc more words on the head? How can i make this?
> pydictor.py --head John --head Mike --head Jane -char 0123456789abcdef -- len 1 1 Not working
> 
> I have a text file and there are names on it and all i need, use these words on the head!
> 
> Thanks

you have many methods reaching it with pydictor:

- use `--conf` function :

```
python pydictor.py --conf "[John,Mike,Jane]{1,1}<none>[0-9,a-f]{1,1}<none>"
```

- using `hybrider` tool:

**step 1. generation common word list, such as /tmp/common.txt** 
```
python pydictor.py -char 0123456789abcdef --len 1 1 -o /tmp/common.txt
```


**step 2. prepared head word list file，such as `/tmp/head.txt`，it's content as following:**

```
John
Mike
Jane
```

**step 3. use hybrider tool**
```
python pydictor.py -tool hybrider /tmp/head.txt /tmp/common.txt
```

**Comment by Uraniumhazee** [comment]
Thanks you are awesome.
Thanks again.
