### ISSUE TITLE
Is there a function like occur and types, that for exemple delete lines below 6 characters?

### ISSUE THREAD

**Issue by Privacy6484847** [LandGrey/pydictor#33]
Is there a function like occur and types, that for exemple delete lines below 6 characters?

**Comment by LandGrey** [comment]
> Is there a function like occur and types, that for exemple delete lines below 6 characters?

Maybe you need using `--len 6 100` option limit characters length?

**Comment by Privacy6484847** [comment]
Thanks for your reply.
I tried this but it doesn't work: `Pydictor.py --len 6 20 test.txt`

**Comment by LandGrey** [comment]
> Pydictor.py --len 6 20 test.txt

Using command `python pydictor.py --len 6 20 -tool handler test.txt` to filter your word list.

**Comment by Privacy6484847** [comment]
This is exactly what i was looking for: `pydictor --len 6 20 -tool handler test.txt`
Thank you very much!! :)

**Comment by LandGrey** [comment]
> This is exactly what i was looking for: `pydictor --len 6 20 -tool handler test.txt` Thank you very much!! :)

you are welcome.
