### ISSUE TITLE
--conf doesn't work for custom build

### ISSUE THREAD

**Issue by irjohn** [LandGrey/pydictor#35]
I'm trying to build a dictionary with a config file that builds for wpa2 keys. It doesn't seem to work when over a certain amount of characters. It acts like it's generating the list but the file is just empty. I'm trying to build this: 
python pydictor.py --conf '[a-z]{6,6}<none>[0-9]{4,4}<none>[a-z]{6,6}<none>'
it just spits out a conf_xxxxxx.txt file with nothing in it. I've edited my data.py to allow for more than the default combinations.

**Comment by LandGrey** [comment]
> I'm trying to build a dictionary with a config file that builds for wpa2 keys. It doesn't seem to work when over a certain amount of characters. It acts like it's generating the list but the file is just empty. I'm trying to build this: python pydictor.py --conf '[a-z]{6,6}[0-9]{4,4}[a-z]{6,6}' it just spits out a conf_xxxxxx.txt file with nothing in it. I've edited my data.py to allow for more than the default combinations.

change your command to `python pydictor.py --conf '[a-z]{6,6}<none>[0-9]{4,4}<none>[a-z]{6,6}<none>'`
