### ISSUE TITLE
--conf build dictionary with "-" as special character

### ISSUE THREAD

**Issue by Slepun** [LandGrey/pydictor#36]
Hi,

I'm trying to build dictionary with --conf as option. Dictionary should contain "-" character.
I tried following: 
sometext[-]{0,1}><none>, sometext[\-]{0,1}<none>, sometext["-"]{0,1}<none>, sometext['-']{0,1}<none>

But none of this works. Is it possible to use "-" in this context?
Besides, the tool is exactly what I was needed. Good job!

BR\
Slepun

**Comment by LandGrey** [comment]
> Hi,
> 
> I'm trying to build dictionary with --conf as option. Dictionary should contain "-" character. I tried following: sometext[-]{0,1}>, sometext[-]{0,1}, sometext["-"]{0,1}, sometext['-']{0,1}
> 
> But none of this works. Is it possible to use "-" in this context? Besides, the tool is exactly what I was needed. Good job!
> 
> BR Slepun

First, download the latest pydictor version `2.1.7.1`,
Then reference https://github.com/LandGrey/pydictor/blob/master/funcfg/extend.conf file special char map table
You can use `%-%` to replace `-` character in `--conf` function.

**Comment by Slepun** [comment]
Works for me. 谢谢！

BR\
Slepun
