### ISSUE TITLE
unsupported operand type(s) for +: 'generator' and 'generator'

### ISSUE THREAD

**Issue by DojoKuro** [LandGrey/pydictor#37]
```
pydictor SEDB>>show                                                                                      
len        : minlen: [no-limited] maxlen: [no-limited]             
head       : [none]                                                                                      
tail       : [none]                                                                                      
encode     : [none]                                                                                      
occur      : letter: [ <=99 ] digital: [ <=99 ] special: [ <=99  ]    
types      : letter: [ >=0  ] digital: [ >=0  ] special: [ >=0   ]
repeat     : letter: [ >=0  ] digital: [ >=0  ] special: [ >=0   ]
level      : [3]                                                                                         
leet       : [none]                                                                                      
regex      : [.*?]                                                                                       
cname      :liwei                                                                                        
ename      :zwell                                                                                        
sname      :lw Lwei                                                                                      
birth      :19880916            
usedpwd    :liwei123456. liwei@19880916 lw19880916_123                                                   
phone      :18852006666       
uphone     :15500998080
hphone     :76500100 61599000 01061599000
email      :33125500@qq.com 13561207878@163.com weiweili@gmail.com wei010wei@hotmail.com                 
postcode   :663321 962210                                                                                
nickname   :zlili                                                                                        
idcard     :152726198809160571      
jobnum     :20051230 100563
otherdate  :19591004 19621012 19870906 19880208
usedchar   :tiger gof gamesthrones 176003 m0n5ter ppdog                                                  
pydictor SEDB>>run                                                                                       
single rule                              
unsupported operand type(s) for +: 'generator' and 'generator'
```
社公字典生成时报错，什么问题？

**Comment by LandGrey** [comment]
> ```
> pydictor SEDB>>show                                                                                      
> len        : minlen: [no-limited] maxlen: [no-limited]             
> head       : [none]                                                                                      
> tail       : [none]                                                                                      
> encode     : [none]                                                                                      
> occur      : letter: [ <=99 ] digital: [ <=99 ] special: [ <=99  ]    
> types      : letter: [ >=0  ] digital: [ >=0  ] special: [ >=0   ]
> repeat     : letter: [ >=0  ] digital: [ >=0  ] special: [ >=0   ]
> level      : [3]                                                                                         
> leet       : [none]                                                                                      
> regex      : [.*?]                                                                                       
> cname      :liwei                                                                                        
> ename      :zwell                                                                                        
> sname      :lw Lwei                                                                                      
> birth      :19880916            
> usedpwd    :liwei123456. liwei@19880916 lw19880916_123                                                   
> phone      :18852006666       
> uphone     :15500998080
> hphone     :76500100 61599000 01061599000
> email      :33125500@qq.com 13561207878@163.com weiweili@gmail.com wei010wei@hotmail.com                 
> postcode   :663321 962210                                                                                
> nickname   :zlili                                                                                        
> idcard     :152726198809160571      
> jobnum     :20051230 100563
> otherdate  :19591004 19621012 19870906 19880208
> usedchar   :tiger gof gamesthrones 176003 m0n5ter ppdog                                                  
> pydictor SEDB>>run                                                                                       
> single rule                              
> unsupported operand type(s) for +: 'generator' and 'generator'
> ```
> 
> 社公字典生成时报错，什么问题？

上次更新有个 bug，目前已解决，github 重新下载最新版试用。
