### ISSUE TITLE
How to specify how many passwords wanted?

### ISSUE THREAD

**Issue by Saydemr** [LandGrey/pydictor#39]
Hello,

I looked through the document and could not find any parameter to pass so that the program stops after creating that many passwords. Is there any parameter like that? Could you add this functionality if not?

Thanks.

**Comment by LandGrey** [comment]
> the program stops

sorry, the program cannot stops during the running.

**Comment by mehedehasanontor1** [comment]
https://www.facebook.com/mehedi09khushi

**Comment by mehedehasanontor1** [comment]
hack plz

**Comment by Maraj3928** [comment]
How to get access insta accounts someones need access about account for any one instagram account user ??🥺💔🥀
