### ISSUE TITLE
No Hybrid dictionary generation

### ISSUE THREAD

**Issue by sagerpager** [LandGrey/pydictor#4]
i wish to create a 10 digit phone number word list where the first 4 digits are fixed (they are 115 in total) the rest 6 digits can be anywhere ranging from 000000-999999. i have the first 4 words (115 in number) in a file named codes.txt and the rest 6 digits all possible numbers in another file named all6.txt. How do i crate a word list such that the first 4 numbers are always fixed from codes.txt and the rest 6 from all6.txt.?? 
Can pydictor do it ?
What command would be used ?

Sorry i am a newbie and unable to find my way around

**Comment by LandGrey** [comment]
pydictor can do that. Just use --conf function, like: 
`python pydictor.py --conf "[/path/to/codes.txt]{1,1}<none>[/path/to/all6.txt]{1,1}<none>" -o phone_number.txt`
But it will cost long time and huge memerys to generate the word list, So I wrote a new tool to deal with that, you need to download the newest pydictor and use command like:
`python pydictor.py -tool hybrider /path/to/codes.txt /path/to/all6.txt -o phone_number.txt`
you can get hybrid word list you want.

**Comment by sagerpager** [comment]
Thanks man it was a great help. You rock. However this hybrid tool doesn't generate verbose on screen that how many lines will be created or what is the progress.

**Comment by sagerpager** [comment]
Thanks man it was a great help. You rock. However this hybrid tool doesn't generate verbose on screen that how many lines will be created or what is the progress.
