### ISSUE TITLE
Options --occur and --types not filtering

### ISSUE THREAD

**Issue by danicuestasuarez** [LandGrey/pydictor#7]
I'm trying to achieve the following:

`python pydictor/pydictor.py --len 4 8 --output dictionary -char abcdefg123 --types "" "<=2" "==0" --occur "<=1" "<=2" "==0"`

Which means producing combinations of those unique letters and at most 2 of the specified numbers (which could be repeated)
Also tried switching them around, just in case i was making a mistake, like this:

`python pydictor/pydictor.py --len 4 8 --output dictionary -char abcdefg123 --occur "" "<=2" "==0" --types "<=1" "<=2" "==0"`

But nope, both generate the same huge dictionary with repeated letters. They're not filtering at all.

**Comment by LandGrey** [comment]
Thank you for your feedback after using pydictor.
You can find the descriptions in README file that **"-char" option only support "F1 F2 F3 F4" functions**,
so using "--types" and "--occur" options does not worked.
You can run 
```
python pydictor/pydictor.py --conf "[a-f,1-3]{4,8}<none>" --output dictionary --occur "<=1" "<=2" "==0" --types "" "<=2" "==0"
```
OR
```
python pydictor/pydictor.py --len 4 8 --output all-wordlist.txt -char abcdefg123"
python pydictor/pydictor.py -tool handler all-wordlist.txt --output dictionary --occur "<=1" "<=2" "==0" --types "" "<=2" "==0"
```
command get your wordlist.

**Comment by LandGrey** [comment]
as you see, --conf option can worked well for your senior -char option purpose, but it's will be cost long time sometimes due to some filter functions. so I temporarily attend to don't add extra functionality for -char option although it's every easy to implement.
