### ISSUE TITLE
pydictor not defined

### ISSUE THREAD

**Issue by amylovie** [LandGrey/pydictor#8]
since im a bit noob, i think im doing something wrong. i opened the code, pressed f5, and tried the sedb. >>pydictor.py --sedb and tells me pydctor is not defined?, how im supposed to open the code? i mean i edit with idle->f5 and wrote pydictor.py --sedb, i tried just --sedb and also doesnt let me get  in, please help!

**Comment by LandGrey** [comment]
Please don't run pydictor in idle console, use system shell console (like dos or bash), enter into the pydictor folder,  press 'python pydictor.py --sedb' command.
